project_id = "hazvvrvkpeqzsiaejfil"

[functions.evaluate-idea]
verify_jwt = false

[functions.expert-analysis]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.creative-hint]
verify_jwt = false
